import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import GlobalNav from "../components/global-nav";
import { ModeToggle } from "@/components/theme/mode-toggle";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@/components/theme/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppRouterCacheProvider options={{ key: "css" }}>
            <header className="border-b h-16 flex items-center font-bold text-2xl px-4 justify-between">
              <p>React Hook Form Dev</p>
              <ModeToggle />
            </header>
            <div className="grid grid-cols-12">
              <div className="col-span-2">
                <GlobalNav />
              </div>
              <main className="col-span-10 p-4">{children}</main>
            </div>
          </AppRouterCacheProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
